baseURL: https://adrienduverger.netlify.app/
languageCode: en-us
title: Adrien
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Currently reading for the MFA 2022 at London Business School
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Portfolio website for Adrien Duverger
  blog: {}
  contact:
    address:
      - city: London,
        country: United Kingdom
        street: Sussex Place, NW1 4SA
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: aduverger.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (020) 7000 7000
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/LBS?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/LondonBusinessSchool/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/londonbschool/?hl=fr
      - icon: fa-github
        label: GitHub
        url: https://github.com/adriendvrg
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/adrien-duverger/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Browse
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Portfolio Website
    title: Adrien Duverger
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: My Past Experiences
        title: About Me
        url: blogs/about_me
      - image: DJ.jpg
        subtitle: Analysis of Dow Jones Stocks using R
        title: Risk Return of DJIA Industrial Average
        url: blogs/risk_return
      - image: pic03.jpg
        subtitle: CPI components analyis using R
        title: CPI Analysis
        url: blogs/CPI
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Browse
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
